import { useEffect, useRef, useState } from 'react';
import { applyHumanoid, initialHumanoid, roles, type Joint, type HumanoidDraft } from '../characters';
import { type Project, type Scene, type Rig, id } from '../model';
import { Engine } from '../engine';
import { Renderer } from '../renderer';
import { Stage } from './Stage';
import { t, tr } from '../i18n';
export function RigWizard({project,scene,engine,onApply,onCancel}:{project:Project;scene:Scene;engine:Engine;onApply:(p:Project,root:string)=>void;onCancel:()=>void}){
  const [draft,setDraft]=useState(()=>initialHumanoid(project,scene)),[step,setStep]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Project|null>(null),[root,setRoot]=useState(''),[bone,setBone]=useState(''),canvas=useRef<HTMLCanvasElement>(null),drag=useRef<Joint|null>(null);
  useEffect(()=>{if(step!==1)return;let alive=true;const renderer=new Renderer(canvas.current!);void engine.evaluate(project,{...scene,tracks:[],clips:[]},0).then(frame=>{if(alive)return renderer.render(project,frame,project.width,project.height);}).catch(e=>setError(e.message));return()=>{alive=false;renderer.dispose();};},[step]);
  async function prepare(){setBusy(true);setError('');try{const p=structuredClone(project),s=p.scenes.find(s=>s.id===scene.id)!,prepared=new Map<string,Rig>(),frame=await engine.evaluate(project,{...scene,tracks:[],clips:[]},0);for(const layerId of Object.values(draft.assignments)){if(!layerId)continue;const l=scene.layers.find(l=>l.id===layerId)!,asset=project.assets.find(a=>a.id===l.assetId)!;const mesh=await engine.mesh(asset,24,4,[]);prepared.set(layerId,{id:id(),revision:1,mesh,pins:[],bones:[],density:24,expansion:4});}const root=applyHumanoid(p,s,draft,frame.worlds!,prepared);setRoot(root);setPreview(p);setStep(2);}catch(e){setError(tr((e as Error).message));}finally{setBusy(false);}}
  function moveJoint(e:React.PointerEvent<SVGSVGElement>){if(!drag.current)return;const rect=e.currentTarget.getBoundingClientRect(),point={x:(e.clientX-rect.left)/rect.width*project.width,y:(e.clientY-rect.top)/rect.height*project.height};setDraft(d=>({...d,joints:{...d.joints,[drag.current!]:point}}));}
  function testDrag(kind:string,id:string,value:any){if(kind!=='bone'||!preview)return;setPreview(old=>{const p=structuredClone(old!),s=p.scenes.find(s=>s.id===scene.id)!,l=s.layers.find(l=>l.id===root)!,r=p.rigs.find(r=>r.id===l.rigId)!,b=r.bones.find(b=>b.id===id)!;if(b.parentId&&b.ikEnabled!==false)b.ikTarget=value;else b.angle=(Math.atan2(value.y-b.start.y,value.x-b.start.x)-Math.atan2(b.end.y-b.start.y,b.end.x-b.start.x))*180/Math.PI;return p;});}
  return <div className="modal-backdrop"><section className="modal wizard-modal"><div className="modal-title"><h2>{t('Humanoid assistant')}</h2><button onClick={onCancel} aria-label={t('Cancel')}>×</button></div><div className="wizard-steps">{['Assign parts','Place joints','Test movement'].map((label,i)=><span className={step===i?'active':''} key={label}>{i+1}. {tr(label)}</span>)}</div>
    {step===0?<><label className="text-field">{t('Name')}<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="checkbox"><input type="checkbox" checked={draft.copy} onChange={e=>setDraft({...draft,copy:e.target.checked})}/>{t('Work on a copy')}</label><div className="part-assignment">{roles.map(role=><label className="select-field" key={role}>{t(role)}<select aria-label={t(role)} value={draft.assignments[role]??''} onChange={e=>setDraft({...draft,assignments:{...draft.assignments,[role]:e.target.value||undefined}})}><option value="">{t('None')}</option>{scene.layers.filter(l=>l.kind==='image').map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>)}</div></>:step===1?<div className="joint-canvas" style={{aspectRatio:project.width/project.height}}><canvas ref={canvas}/><svg viewBox={`0 0 ${project.width} ${project.height}`} onPointerMove={moveJoint} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>{Object.entries(draft.joints).map(([joint,p])=><g key={joint}><circle cx={p.x} cy={p.y} r={project.width/70} fill="#bdabff" stroke="#191923" strokeWidth={3} onPointerDown={e=>{drag.current=joint as Joint;e.currentTarget.ownerSVGElement?.setPointerCapture(e.pointerId);}}/><text x={p.x+project.width/60} y={p.y} fontSize={project.width/90} fill="#fff" stroke="#191923" paintOrder="stroke" strokeWidth={3}>{tr(joint)}</text></g>)}</svg></div>:preview&&<div className="wizard-preview"><Stage project={preview} sceneId={scene.id} time={0} engine={engine} selectedLayer={root} selectedPin="" selectedBone={bone} tool="select" meshVisible={false} onion={false} preview={.5} onSelectPin={()=>{}} onSelectBone={setBone} onSelectLayer={()=>{}} onCreatePin={()=>{}} onCreateBone={()=>{}} onDrag={testDrag} onError={setError} playing={false}/></div>}
    {error&&<p role="alert" className="wizard-error">{error}</p>}<div className="modal-actions"><button onClick={step?()=>{setStep(step-1);setError('');}:onCancel}>{t(step?'Back':'Cancel')}</button><button className="primary-button" disabled={busy||!draft.assignments.torso||!draft.name.trim()} onClick={()=>{if(step===0){setStep(1);setError('');}else if(step===1)void prepare();else if(preview){const p=structuredClone(preview),s=p.scenes.find(s=>s.id===scene.id)!,r=p.rigs.find(r=>r.id===s.layers.find(l=>l.id===root)!.rigId)!;for(const b of r.bones){b.angle=0;delete b.ikTarget;}onApply(p,root);}}}>{busy?'…':t(step===2?'Apply character':'Next')}</button></div>
  </section></div>;
}
