import { canConnect, connectedPieceIds } from '../connections';
import { t, tr } from '../i18n';
import { layerMatrix } from '../transforms';
import { type CSSProperties, useEffect, useRef, useState } from 'react';
import { Maximize2, Minus, Plus, ScanLine, Layers, Move, MousePointer2, Pin, Bone, Paintbrush } from 'lucide-react';
import { type Project, type EvaluatedScene, type Point, type PinKind, type Bone as BoneType, type Mesh } from '../model';
import { Engine } from '../engine';
import { Renderer, applyMatrix, cameraMatrix, multiply, inverseMatrix } from '../renderer';
import { evaluateControls, sampleTrack } from '../animation';
import { bonePoses } from '../rigging';
export type Tool = 'select'|'translate'|PinKind|'bone'|'weight'|'connect';
type Props={project:Project;sceneId:string;time:number;engine:Engine;selectedLayer:string;selectedPin:string;selectedBone:string;tool:Tool;meshVisible:boolean;onion:boolean;preview:number;onSelectPin:(id:string)=>void;onSelectBone:(id:string)=>void;onSelectLayer:(id:string)=>void;onCreatePin:(point:Point)=>void;onCreateBone:(start:Point,end:Point)=>void;onDrag:(kind:'pin'|'layer'|'bone'|'weight'|'path'|'transform',id:string,value:any,done:boolean)=>void;onError:(message:string)=>void;playing:boolean;selectedLayers?:string[];onSelectPart?:(id:string)=>void;onConnectTarget?:(target:import('../model').LayerAttachment)=>void;}
export function Stage(props:Props){
  const canvas=useRef<HTMLCanvasElement>(null),renderer=useRef<Renderer|null>(null),ghostRenderer=useRef<Renderer|null>(null),pending=useRef<Props|null>(null),running=useRef(false),alive=useRef(true),[frame,setFrame]=useState<EvaluatedScene|null>(null),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[ghostImages,setGhostImages]=useState<string[]>([]),[drawing,setDrawing]=useState<{start:Point;end:Point}|null>(null),[fps,setFps]=useState(0),[hover,setHover]=useState(''),[gizmo,setGizmo]=useState<'rotate'|'scale'|null>(null),lastFrame=useRef(performance.now());
  const drag=useRef<{kind:'pin'|'layer'|'bone'|'weight'|'path'|'transform'|'pan';id:string;start:Point;original:any;last:any}|null>(null),overlay=useRef<SVGSVGElement>(null);
  useEffect(()=>{alive.current=true;try{renderer.current=new Renderer(canvas.current!);}catch(e){props.onError((e as Error).message);}return()=>{alive.current=false;renderer.current?.dispose();ghostRenderer.current?.dispose();};},[]);
  useEffect(()=>{pending.current=props;if(running.current)return;async function pump(){running.current=true;while(pending.current&&alive.current){const p=pending.current;pending.current=null;try{const scene=p.project.scenes.find(s=>s.id===p.sceneId)!;const evaluated=await p.engine.evaluate(p.project,scene,p.time);if(!alive.current)break;await renderer.current?.render(p.project,evaluated,Math.round(p.project.width*p.preview),Math.round(p.project.height*p.preview));setFrame(evaluated);const now=performance.now();setFps(Math.round(1000/Math.max(1,now-lastFrame.current)));lastFrame.current=now;if(p.onion&&!p.playing){const step=p.project.fps.denominator/p.project.fps.numerator;const ghosts=await Promise.all([p.engine.evaluate(p.project,scene,Math.max(0,p.time-step*3)),p.engine.evaluate(p.project,scene,Math.min(scene.duration,p.time+step*3))]);ghostRenderer.current??=new Renderer(document.createElement('canvas'));const images:string[]=[];for(const ghost of ghosts){await ghostRenderer.current.render(p.project,{...ghost,scene:{...ghost.scene,camera:evaluated.scene.camera}},Math.round(p.project.width*p.preview),Math.round(p.project.height*p.preview),true);images.push(ghostRenderer.current.canvas.toDataURL('image/png'));}if(alive.current)setGhostImages(images);}else setGhostImages([]);}catch(e){props.onError((e as Error).message);}}running.current=false;}void pump();},[props.project,props.sceneId,props.time,props.preview,props.onion,props.playing]);
  const scene=props.project.scenes.find(s=>s.id===props.sceneId)!,evaluated=frame?.layers.find(l=>l.id===props.selectedLayer),source=scene.layers.find(l=>l.id===props.selectedLayer),rig=frame?.rigs?.[props.selectedLayer]??evaluated?.rig??props.project.rigs.find(r=>r.id===source?.rigId);
  const camera=frame?cameraMatrix(props.project,frame):[1,0,0,1,0,0],matrix=frame?.worlds?.[props.selectedLayer]?multiply(camera,frame.worlds[props.selectedLayer]):evaluated?multiply(camera,evaluated.world):[1,0,0,1,source?.transform.position.x??0,source?.transform.position.y??0],inverse=inverseMatrix(matrix);
  function point(event:React.MouseEvent){const rect=overlay.current!.getBoundingClientRect();return {x:(event.clientX-rect.left)/rect.width*props.project.width,y:(event.clientY-rect.top)/rect.height*props.project.height};}
  function local(event:React.PointerEvent){return applyMatrix(inverse,point(event));}
  function hitLayer(event:React.MouseEvent){const cursor=point(event);for(const layer of frame?.layers??[]){if(layer.locked)continue;const q=applyMatrix(inverseMatrix(multiply(camera,layer.world)),cursor),triangles=layer.rig?.mesh.triangles??[0,1,2,0,2,3],v=layer.vertices;for(let i=0;i<triangles.length;i+=3){const a=triangles[i]*2,b=triangles[i+1]*2,c=triangles[i+2]*2,cross=(ax:number,ay:number,bx:number,by:number)=>ax*by-ay*bx,d1=cross(v[b]-v[a],v[b+1]-v[a+1],q.x-v[a],q.y-v[a+1]),d2=cross(v[c]-v[b],v[c+1]-v[b+1],q.x-v[b],q.y-v[b+1]),d3=cross(v[a]-v[c],v[a+1]-v[c+1],q.x-v[c],q.y-v[c+1]);if((d1>=0&&d2>=0&&d3>=0)||(d1<=0&&d2<=0&&d3<=0))return layer.id;}}return '';}
  function connectHit(event:React.PointerEvent){const cursor=point(event),rect=overlay.current!.getBoundingClientRect(),radius=14*props.project.width/rect.width;for(const layer of scene.layers){if(props.selectedLayers?.includes(layer.id)||layer.locked||props.selectedLayers?.some(id=>!canConnect(scene,id,layer.id)))continue;const r=frame?.rigs?.[layer.id],m=frame?.worlds?.[layer.id];if(!r||!m)continue;const mat=multiply(camera,m);for(const pin of r.pins){const q=applyMatrix(mat,pin.position);if(Math.hypot(q.x-cursor.x,q.y-cursor.y)<radius)return {layerId:layer.id,kind:'pin' as const,controlId:pin.id};}const poses=bonePoses(r.bones);for(const b of r.bones){const pose=poses.get(b.id)!,dx=b.end.x-b.start.x,dy=b.end.y-b.start.y,q=applyMatrix(mat,{x:pose.start.x+Math.cos(pose.angle)*dx-Math.sin(pose.angle)*dy,y:pose.start.y+Math.sin(pose.angle)*dx+Math.cos(pose.angle)*dy});if(Math.hypot(q.x-cursor.x,q.y-cursor.y)<radius)return {layerId:layer.id,kind:'bone' as const,controlId:b.id};}}const layerId=hitLayer(event);if(layerId&&props.selectedLayers?.filter(id=>id!==layerId).some(id=>!canConnect(scene,id,layerId)))return undefined;return layerId?{layerId,kind:'layer' as const}:undefined;}
  function fitSelection(){const ids=connectedPieceIds(scene,props.selectedLayer),points=(frame?.layers??[]).filter(l=>ids.has(l.id)).flatMap(l=>Array.from({length:l.vertices.length/2},(_,i)=>applyMatrix(multiply(camera,l.world),{x:l.vertices[i*2],y:l.vertices[i*2+1]})));if(!points.length)return;const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y)),z=Math.max(.3,Math.min(3,.8*Math.min(props.project.width/(maxX-minX||1),props.project.height/(maxY-minY||1)))),rect=overlay.current!.getBoundingClientRect(),baseW=rect.width/zoom,baseH=rect.height/zoom;setZoom(z);setPan({x:(.5-(minX+maxX)/2/props.project.width)*baseW*z,y:(.5-(minY+maxY)/2/props.project.height)*baseH*z});}
  function startTransform(event:React.PointerEvent,kind:'rotate'|'scale'){event.stopPropagation();if(!source||source.locked)return;const active=frame?.scene.layers.find(l=>l.id===source.id)??source,pivot=applyMatrix(matrix,{x:0,y:0}),p=point(event);setGizmo(kind);drag.current={kind:'transform',id:source.id,start:p,original:{pivot,transform:active.transform,angle:Math.atan2(p.y-pivot.y,p.x-pivot.x),distance:Math.hypot(p.x-pivot.x,p.y-pivot.y)},last:{path:kind==='rotate'?'transform/rotation':'transform/scale',value:kind==='rotate'?active.transform.rotation:active.transform.scale}};overlay.current?.setPointerCapture(event.pointerId);}
  function down(event:React.PointerEvent){if(event.button===1||event.altKey){drag.current={kind:'pan',id:'',start:{x:event.clientX,y:event.clientY},original:pan,last:pan};overlay.current?.setPointerCapture(event.pointerId);event.preventDefault();return;}if(event.button===0&&props.tool==='connect'){const target=connectHit(event);if(target)props.onConnectTarget?.(target);return;}if(event.button!==0)return;if(source?.locked||evaluated?.locked){const hit=hitLayer(event);if(hit)props.onSelectLayer(hit);return;}const p=local(event);overlay.current?.setPointerCapture(event.pointerId);
    if(props.tool==='bone'){setDrawing({start:p,end:p});return;}
    if(props.tool==='weight'&&props.selectedBone){drag.current={kind:'weight',id:props.selectedBone,start:p,original:null,last:p};props.onDrag('weight',props.selectedBone,p,false);return;}
    if(!['select','translate'].includes(props.tool)){props.onCreatePin(p);return;}
    if(props.tool==='translate'){if(!source)return;const position=frame?.scene.layers.find(l=>l.id===source.id)?.transform.position??source.transform.position;drag.current={kind:'layer',id:source.id,start:point(event),original:position,last:position};return;}
    const rect=overlay.current!.getBoundingClientRect(),radius=14*props.project.width/rect.width;
    const cursor=point(event),pin=rig?.pins.find(p=>{const q=applyMatrix(matrix,p.position);return Math.hypot(q.x-cursor.x,q.y-cursor.y)<radius;});
    if(pin){props.onSelectPin(pin.id);if(pin.kind==='fixed'||pin.kind==='stiff'||pin.kind==='overlap')return;drag.current={kind:'pin',id:pin.id,start:p,original:pin.position,last:pin.position};return;}
    for(const bone of rig?.bones??[]){const pose=bonePoses(rig!.bones).get(bone.id)!,dx=bone.end.x-bone.start.x,dy=bone.end.y-bone.start.y,localTip={x:pose.start.x+Math.cos(pose.angle)*dx-Math.sin(pose.angle)*dy,y:pose.start.y+Math.sin(pose.angle)*dx+Math.cos(pose.angle)*dy},tip=applyMatrix(matrix,localTip);if(Math.hypot(tip.x-point(event).x,tip.y-point(event).y)<radius){props.onSelectBone(bone.id);drag.current={kind:'bone',id:bone.id,start:p,original:localTip,last:localTip};return;}}
    // Hit-test the actual deformed triangles, from front to back.
    for(const layer of frame?.layers??[]){if(layer.locked)continue;const m=multiply(camera,layer.world),q=applyMatrix(inverseMatrix(m),point(event)),triangles=layer.rig?.mesh.triangles??[0,1,2,0,2,3],v=layer.vertices;let hit=false;for(let i=0;i<triangles.length;i+=3){const a=triangles[i]*2,b=triangles[i+1]*2,c=triangles[i+2]*2;const cross=(ax:number,ay:number,bx:number,by:number)=>ax*by-ay*bx;const d1=cross(v[b]-v[a],v[b+1]-v[a+1],q.x-v[a],q.y-v[a+1]),d2=cross(v[c]-v[b],v[c+1]-v[b+1],q.x-v[b],q.y-v[b+1]),d3=cross(v[a]-v[c],v[a+1]-v[c+1],q.x-v[c],q.y-v[c+1]);if((d1>=0&&d2>=0&&d3>=0)||(d1<=0&&d2<=0&&d3<=0)){hit=true;break;}}if(hit){props.onSelectLayer(layer.id);return;}}
  }
  function move(event:React.PointerEvent){if(props.tool==='connect'){setHover(connectHit(event)?.layerId??'');return;}if(drawing){setDrawing({...drawing,end:local(event)});return;}const d=drag.current;if(!d)return;if(d.kind==='pan'){setPan({x:d.original.x+event.clientX-d.start.x,y:d.original.y-d.start.y+event.clientY});return;}if(d.kind==='transform'){const p=point(event),o=d.original,value=gizmo==='rotate'?{path:'transform/rotation',value:o.transform.rotation+(Math.atan2(p.y-o.pivot.y,p.x-o.pivot.x)-o.angle)*180/Math.PI}:{path:'transform/scale',value:{x:Math.max(.01,o.transform.scale.x*Math.hypot(p.x-o.pivot.x,p.y-o.pivot.y)/(o.distance||1)),y:Math.max(.01,o.transform.scale.y*Math.hypot(p.x-o.pivot.x,p.y-o.pivot.y)/(o.distance||1))}};d.last=value;props.onDrag('transform',d.id,value,false);return;}const p=d.kind==='layer'?point(event):local(event);let value:any=p;if(d.kind==='path')value={side:d.original.side,point:{x:p.x-d.original.value.x,y:p.y-d.original.value.y}};if(d.kind==='pin'||d.kind==='layer'){let delta={x:p.x-d.start.x,y:p.y-d.start.y};if(d.kind==='layer'){const active=frame?.scene.layers.find(l=>l.id===source?.id),world=active&&frame?.worlds?.[active.id];const parentMatrix=active&&world?multiply(camera,multiply(world,inverseMatrix(layerMatrix(active.transform)))):camera;const inv=inverseMatrix(parentMatrix);delta={x:inv[0]*delta.x+inv[2]*delta.y,y:inv[1]*delta.x+inv[3]*delta.y};}value={x:d.original.x+delta.x,y:d.original.y+delta.y};}d.last=value;props.onDrag(d.kind,d.id,value,false);}
  function up(){if(drawing){props.onCreateBone(drawing.start,drawing.end);setDrawing(null);}const d=drag.current;if(d&&d.kind!=='pan')props.onDrag(d.kind,d.id,d.last,true);drag.current=null;setGizmo(null);}
  const colors:Record<string,string>={move:'#f8bf6b',fixed:'#adbbcc',stiff:'#e88791',transform:'#ae9dff',overlap:'#80bee4'};
  function wire(mesh:Mesh,vertices:ArrayLike<number>,m:number[],color:string,opacity=.2){return <path d={mesh.triangles.reduce((path,_,i,indices)=>{if(i%3)return path;const a=applyMatrix(m,{x:vertices[indices[i]*2],y:vertices[indices[i]*2+1]}),b=applyMatrix(m,{x:vertices[indices[i+1]*2],y:vertices[indices[i+1]*2+1]}),c=applyMatrix(m,{x:vertices[indices[i+2]*2],y:vertices[indices[i+2]*2+1]});return `${path}M${a.x},${a.y}L${b.x},${b.y}L${c.x},${c.y}Z`;},'')} fill="none" stroke={color} strokeWidth="1" opacity={opacity} vectorEffect="non-scaling-stroke"/>;}
  const motionTrack=scene.tracks.find(t=>t.targetId===props.selectedLayer&&t.property===`rig/pins/${props.selectedPin}/position`);
  return <section className="stage-panel">
    <div className="stage-header"><div className="breadcrumb">{tr("PROJECT")} <span>/</span> <strong>{scene.name}</strong></div><div className="stage-meta"><span className="status-dot"/> {props.project.width} × {props.project.height}<span className="subtle">{props.project.fps.numerator/props.project.fps.denominator} {tr("fps")}</span></div></div>
    <div className="stage-tools"><button className={props.tool==='select'?'active':''} title={tr("Select · V")} onClick={()=>document.dispatchEvent(new CustomEvent('puppet:tool',{detail:'select'}))}><MousePointer2 size={17}/></button><button className={props.tool==='translate'?'active':''} title={tr("Move layer · G")} onClick={()=>document.dispatchEvent(new CustomEvent('puppet:tool',{detail:'translate'}))}><Move size={17}/></button><span className="divider"/><button className={props.tool==='move'||props.tool==='fixed'?'active':''} title={tr("Movement pin · P")} onClick={()=>document.dispatchEvent(new CustomEvent('puppet:tool',{detail:'move'}))}><Pin size={17}/></button><button className={props.tool==='bone'?'active':''} title={tr("Draw bone · B")} onClick={()=>document.dispatchEvent(new CustomEvent('puppet:tool',{detail:'bone'}))}><Bone size={18}/></button><button className={props.tool==='weight'?'active':''} title={tr("Paint selected bone weights")} onClick={()=>document.dispatchEvent(new CustomEvent('puppet:tool',{detail:'weight'}))}><Paintbrush size={17}/></button></div>
    <div className="stage-viewport" onWheel={e=>{if(e.ctrlKey){e.preventDefault();const rect=e.currentTarget.getBoundingClientRect(),next=Math.max(.3,Math.min(3,zoom-e.deltaY*.002)),cx=e.clientX-rect.left-rect.width/2,cy=e.clientY-rect.top-rect.height/2;setPan({x:cx-(cx-pan.x)*next/zoom,y:cy-(cy-pan.y)*next/zoom});setZoom(next);}}}>
      <div className="artboard" style={{'--project-aspect-ratio':props.project.width/props.project.height,transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`} as CSSProperties}>
        <canvas ref={canvas}/><svg ref={overlay} onDoubleClick={e=>{const hit=hitLayer(e);if(hit)props.onSelectPart?.(hit);}} viewBox={`0 0 ${props.project.width} ${props.project.height}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} className={`stage-overlay tool-${props.tool}`}>
          {props.tool==='connect'&&scene.layers.filter(l=>!props.selectedLayers?.includes(l.id)).map(l=>{const r=frame?.rigs?.[l.id],world=frame?.worlds?.[l.id];if(!r||!world)return null;const mat=multiply(camera,world),poses=bonePoses(r.bones);return <g key={l.id} pointerEvents="none">{r.pins.map(pin=>{const q=applyMatrix(mat,pin.position);return <circle key={pin.id} cx={q.x} cy={q.y} r={12} fill="#e9c593" stroke="#24202e" strokeWidth={3}/>;})}{r.bones.map(b=>{const pose=poses.get(b.id)!,dx=b.end.x-b.start.x,dy=b.end.y-b.start.y,a=applyMatrix(mat,pose.start),q=applyMatrix(mat,{x:pose.start.x+Math.cos(pose.angle)*dx-Math.sin(pose.angle)*dy,y:pose.start.y+Math.sin(pose.angle)*dx+Math.cos(pose.angle)*dy});return <g key={b.id}><line x1={a.x} y1={a.y} x2={q.x} y2={q.y} stroke="#b9a1e0" strokeWidth={4}/><circle cx={q.x} cy={q.y} r={12} fill="#b9a1e0"/></g>;})}</g>;})}
          {props.tool==='connect'&&scene.layers.filter(l=>l.attachment).map(l=>{const a=frame?.worlds?.[l.id],b=frame?.worlds?.[l.attachment!.layerId];if(!a||!b)return null;const p=applyMatrix(camera,{x:a[4],y:a[5]}),q=applyMatrix(camera,{x:b[4],y:b[5]});return <line key={l.id} x1={p.x} y1={p.y} x2={q.x} y2={q.y} stroke="#bda6f6" strokeDasharray="7 5" strokeWidth={2} pointerEvents="none"/>;})}
          {props.tool==='connect'&&hover&&<text x={20} y={40} fontSize={25} fill="#fff" stroke="#111" strokeWidth={3} paintOrder="stroke">{t('Connect')} → {scene.layers.find(l=>l.id===hover)?.name}</text>}
          {source&&!source.locked&&['select','translate'].includes(props.tool)&&(()=>{const pivot=applyMatrix(matrix,{x:0,y:0});return <g><circle cx={pivot.x} cy={pivot.y} r={12} fill="#f1c483" onPointerDown={e=>{e.stopPropagation();const position=frame?.scene.layers.find(l=>l.id===source.id)?.transform.position??source.transform.position;drag.current={kind:'layer',id:source.id,start:point(e),original:position,last:position};overlay.current?.setPointerCapture(e.pointerId);}}/><circle aria-label={t('Rotate')} cx={pivot.x} cy={pivot.y-90} r={14} fill="#bba5ee" onPointerDown={e=>startTransform(e,'rotate')}/><rect aria-label={t('Scale')} x={pivot.x+76} y={pivot.y-14} width={28} height={28} fill="#8ec4c0" onPointerDown={e=>startTransform(e,'scale')}/></g>;})()}
          <defs><filter id="onion-before"><feColorMatrix type="matrix" values="0 0 0 0 .25 0 0 0 0 .55 0 0 0 0 1 0 0 0 1 0"/></filter><filter id="onion-after"><feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 .3 0 0 0 0 .5 0 0 0 1 0"/></filter></defs>
          {props.onion&&!props.playing&&ghostImages.map((href,i)=><image className="onion-ghost-image" key={i} href={href} width={props.project.width} height={props.project.height} opacity={.16} filter={`url(#onion-${i?'after':'before'})`} pointerEvents="none"/>)}
          {props.meshVisible&&rig&&evaluated&&wire(rig.mesh,evaluated.vertices,matrix,'#42545b',.3)}
          {props.tool==='weight'&&rig&&evaluated&&rig.bones.find(b=>b.id===props.selectedBone)?.weights.map((w,i)=>{if(w<.025)return null;const p=applyMatrix(matrix,{x:evaluated.vertices[i*2],y:evaluated.vertices[i*2+1]});return <circle key={i} cx={p.x} cy={p.y} r={4} fill={`rgba(137,109,255,${w})`}/>;})}
          {motionTrack&&<><path d={Array.from({length:101},(_,i)=>{const p=sampleTrack(motionTrack,i/100*scene.duration);if(typeof p!=='object')return '';const q=applyMatrix(matrix,p);return `${i?'L':'M'}${q.x},${q.y}`;}).join(' ')} stroke="#8d77c7" strokeWidth="1.5" fill="none" strokeDasharray="4 4" opacity=".65" vectorEffect="non-scaling-stroke"/>{motionTrack.keys.map(k=>{if(typeof k.value!=='object')return null;const q=applyMatrix(matrix,k.value);return <g key={k.id}><circle cx={q.x} cy={q.y} r={5} fill="#b69dfc"/>{(['inSpatial','outSpatial'] as const).map(side=>{const handle=k[side];if(!handle)return null;const v=k.value as Point,p=applyMatrix(matrix,{x:v.x+handle.x,y:v.y+handle.y});return <g key={side}><line x1={q.x} y1={q.y} x2={p.x} y2={p.y} stroke="#8d77c7"/><circle cx={p.x} cy={p.y} r={8} fill="#fff" stroke="#8d77c7" onPointerDown={e=>{e.stopPropagation();overlay.current?.setPointerCapture(e.pointerId);drag.current={kind:'path',id:k.id,start:local(e),original:{side,value:k.value},last:{side,point:handle}};}}/></g>;})}</g>;})}</>}
          {rig?.bones.map(b=>{const pose=bonePoses(rig.bones).get(b.id)!,dx=b.end.x-b.start.x,dy=b.end.y-b.start.y,a=applyMatrix(matrix,pose.start),z=applyMatrix(matrix,{x:pose.start.x+Math.cos(pose.angle)*dx-Math.sin(pose.angle)*dy,y:pose.start.y+Math.sin(pose.angle)*dx+Math.cos(pose.angle)*dy});return <g key={b.id} opacity={props.playing?.3:.9}><line x1={a.x} y1={a.y} x2={z.x} y2={z.y} stroke={b.id===props.selectedBone?'#baa8ff':'#8b79d4'} strokeWidth="7" strokeLinecap="round"/><circle cx={a.x} cy={a.y} r="12" fill="#343145" stroke="#b9a6ff" strokeWidth="4"/><circle cx={z.x} cy={z.y} r="12" fill="#8c74d7" stroke="#e7deff" strokeWidth="4"/></g>;})}
          {rig?.pins.map(pin=>{const p=applyMatrix(matrix,pin.position),selected=pin.id===props.selectedPin;return <g key={pin.id} opacity={props.playing?.25:1}>{selected&&<circle cx={p.x} cy={p.y} r={25} fill="none" stroke={colors[pin.kind]} strokeWidth="2"/>}<circle cx={p.x} cy={p.y} r={selected?13:11} fill={colors[pin.kind]} stroke="#514747" strokeWidth="4"/>{pin.kind==='fixed'&&<path d={`M${p.x-5},${p.y}h10M${p.x},${p.y-5}v10`} stroke="#514747" strokeWidth="2"/>}{selected&&<text x={p.x+30} y={p.y+7} fill="#394746" fontSize="23" fontWeight="600">{pin.name}</text>}</g>;})}
          {drawing&&<line x1={applyMatrix(matrix,drawing.start).x} y1={applyMatrix(matrix,drawing.start).y} x2={applyMatrix(matrix,drawing.end).x} y2={applyMatrix(matrix,drawing.end).y} stroke="#9b7de1" strokeWidth="7" strokeDasharray="8 6"/>}
        </svg>
      </div>
      <div className="canvas-caption"><span>{tr(props.tool==='bone'?'Drag from a joint to its tip':props.tool==='weight'?'Paint to add influence · select a bone first':['select','translate'].includes(props.tool)?'Drag a pin to bring your artwork to life':'Click artwork to place a pin')}</span></div>
    </div>
    <div className="stage-footer"><div><button title={tr("Zoom out")} onClick={()=>setZoom(z=>Math.max(.3,z-.1))}><Minus size={14}/></button><span>{Math.round(zoom*100)}%</span><button title={tr("Zoom in")} onClick={()=>setZoom(z=>Math.min(3,z+.1))}><Plus size={14}/></button><button title={t("Fit selection")} onClick={fitSelection}><Maximize2 size={14}/></button><button title={tr("Fit canvas")} onClick={()=>{setZoom(1);setPan({x:0,y:0});}}><Maximize2 size={14}/></button></div><div><span className="subtle">{props.playing?`${fps} fps`:tr('Ready')}</span><span className="subtle">{tr("Preview")}</span><select value={props.preview} onChange={e=>document.dispatchEvent(new CustomEvent('puppet:preview',{detail:Number(e.target.value)}))}><option value={1}>{tr("Full")}</option><option value={.5}>{tr("Half")}</option><option value={.25}>{tr("Quarter")}</option></select><button title={tr("Toggle mesh")} className={props.meshVisible?'active':''} onClick={()=>document.dispatchEvent(new CustomEvent('puppet:mesh'))}><ScanLine size={15}/></button><button title={tr("Onion skin")} className={props.onion?'active':''} onClick={()=>document.dispatchEvent(new CustomEvent('puppet:onion'))}><Layers size={15}/></button></div></div>
  </section>;
}
