import { t, tr } from '../i18n';
import { useRef, useState } from 'react';
import { Play, Pause, SkipBack, SkipForward, ChevronDown, ChevronRight, Diamond, Plus, Repeat2, SlidersHorizontal, Minus, Flag, Music2 } from 'lucide-react';
import { type Project, type Keyframe, type AnimationTrack, type Scene } from '../model';
import { sequenceDuration } from '../animation';
type Props={project:Project;scene:Scene;time:number;sequenceTime:number;workspace:string;playing:boolean;loop:boolean;autoKey:boolean;selectedLayer:string;selectedKeys:string[];onSelectLayer:(id:string)=>void;onSelectKeys:(ids:string[])=>void;onSeek:(time:number)=>void;onPlay:()=>void;onLoop:()=>void;onAutoKey:()=>void;onAddKey:()=>void;onMarker:()=>void;onToggleLayer:(id:string)=>void;onRetime:(ids:string[],delta:number,snapFrames?:boolean)=>void;onShot:(id:string,start:number)=>void;onAudio:(id:string,start:number)=>void;onSelectShot:(id:string)=>void;onSelectAudio:(id:string)=>void;onCurve:()=>void;onCopyKeys:()=>void;onPasteKeys:()=>void;onDuplicateKeys:()=>void;}
export function timecode(time:number,fps:number){const frame=Math.round(time*fps),f=frame%Math.round(fps),s=Math.floor(frame/fps)%60,m=Math.floor(frame/fps/60);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}:${String(f).padStart(2,'0')}`;}
export function Timeline(p:Props){const [zoom,setZoom]=useState(1),[scroll,setScroll]=useState(0),[draft,setDraft]=useState<{ids:string[];delta:number;snapFrames:boolean}|null>(null),content=useRef<HTMLDivElement>(null),drag=useRef<{ids:string[];x:number;time:number}|null>(null),box=useRef<{x:number;y:number;additive:boolean}|null>(null),[marquee,setMarquee]=useState<{x:number;y:number;w:number;h:number}|null>(null),[snap,setSnap]=useState<Record<string,boolean>>(()=>{try{return JSON.parse(localStorage.getItem('fio.snapping')??'{"Frames":true,"Playhead":true,"Markers":true,"Keys":true}');}catch{return {Frames:true,Playhead:true,Markers:true,Keys:true};}}),assembling=p.workspace==='assemble',duration=assembling?sequenceDuration(p.project):p.scene.duration,pps=(assembling?Math.max(1,900/duration):115)*zoom,width=Math.max(850,duration*pps+80),fps=p.project.fps.numerator/p.project.fps.denominator,current=assembling?p.sequenceTime:p.time;
  const rows:{id:string;name:string;layerId:string;track?:AnimationTrack;group?:boolean}[]=[];
  for(const layer of p.scene.layers){rows.push({id:layer.id,name:layer.name,layerId:layer.id,group:true});if(!layer.collapsed)for(const track of p.scene.tracks.filter(t=>t.targetId===layer.id)){const rig=p.project.rigs.find(r=>r.id===layer.rigId),segments=track.property.split('/'),control=rig?.pins.find(v=>v.id===segments[2])??rig?.bones.find(v=>v.id===segments[2]);rows.push({id:track.id,name:`${control?.name??(segments[0]==='transform'?'Transform':segments[0])} · ${segments.at(-1)}`,layerId:layer.id,track});}}
  for(const track of p.scene.tracks.filter(t=>t.targetId===p.scene.id))rows.push({id:track.id,name:`Camera · ${track.property.split('/').at(-1)}`,layerId:p.scene.id,track});
  const rowHeight=31,startRow=Math.max(0,Math.floor(scroll/rowHeight)-1),visible=rows.slice(startRow,startRow+12);
  function seek(event:React.PointerEvent){const rect=content.current!.getBoundingClientRect();p.onSeek(Math.max(0,Math.min(duration,(event.clientX-rect.left+content.current!.scrollLeft-220)/pps)));}
  function keyDown(event:React.PointerEvent,k:Keyframe){event.stopPropagation();const ids=event.shiftKey?[...new Set([...p.selectedKeys,k.id])]:p.selectedKeys.includes(k.id)?p.selectedKeys:[k.id];p.onSelectKeys(ids);drag.current={ids,x:event.clientX,time:k.time};event.currentTarget.setPointerCapture(event.pointerId);}
  function keyMove(event:React.PointerEvent){const d=drag.current;if(!d)return;let delta=(event.clientX-d.x)/pps;if(!event.altKey){if(snap.Frames)delta=Math.round(delta*fps)/fps;const targets=[...(snap.Playhead?[current]:[]),...(snap.Markers?p.scene.markers.map(m=>m.time):[]),...(snap.Keys?p.scene.tracks.flatMap(t=>t.keys).filter(k=>!d.ids.includes(k.id)).map(k=>k.time):[])];let best=8/pps;for(const target of targets){const distance=Math.abs(target-(d.time+delta));if(distance<best){best=distance;delta=target-d.time;}}}const keys=p.scene.tracks.flatMap(t=>t.keys).filter(k=>d.ids.includes(k.id));delta=Math.max(-Math.min(...keys.map(k=>k.time)),Math.min(duration-Math.max(...keys.map(k=>k.time)),delta));setDraft({ids:d.ids,delta,snapFrames:!event.altKey&&!!snap.Frames});}
  function keyUp(){if(drag.current&&draft)p.onRetime(drag.current.ids,draft.delta,draft.snapFrames);drag.current=null;setDraft(null);}
  function fit(selection=false){const times=selection?p.scene.tracks.flatMap(t=>t.keys).filter(k=>p.selectedKeys.includes(k.id)).map(k=>k.time):[0,duration];if(!times.length)return;const start=Math.min(...times),end=Math.max(...times),available=(content.current?.clientWidth??1000)-260,base=assembling?Math.max(1,900/duration):115,next=Math.max(.02,Math.min(100,available/(Math.max(1/fps,end-start)*base)));setZoom(next);requestAnimationFrame(()=>{if(content.current)content.current.scrollLeft=Math.max(0,start*base*next-20);});}
  function jump(direction:number){const times=p.scene.tracks.filter(t=>!p.selectedLayer||t.targetId===p.selectedLayer).flatMap(t=>t.keys.map(k=>k.time));const next=direction<0?Math.max(-1,...times.filter(t=>t<current-.25/fps)):Math.min(Infinity,...times.filter(t=>t>current+.25/fps));if(next>=0&&Number.isFinite(next))p.onSeek(next);}
  function boxDown(event:React.PointerEvent){if(event.button!==0)return;const rect=content.current!.getBoundingClientRect();box.current={x:event.clientX-rect.left+content.current!.scrollLeft,y:event.clientY-rect.top+content.current!.scrollTop,additive:event.shiftKey||event.ctrlKey||event.metaKey};content.current?.setPointerCapture(event.pointerId);seek(event);}
  function boxMove(event:React.PointerEvent){const b=box.current;if(!b)return;const rect=content.current!.getBoundingClientRect(),x=event.clientX-rect.left+content.current!.scrollLeft,y=event.clientY-rect.top+content.current!.scrollTop;setMarquee({x:Math.min(x,b.x),y:Math.min(y,b.y),w:Math.abs(x-b.x),h:Math.abs(y-b.y)});}
  function boxUp(){const b=box.current;if(!b)return;const ids=marquee?rows.flatMap((row,i)=>row.track?.keys.filter(k=>{const x=220+k.time*pps,y=34+i*rowHeight+15;return x>=marquee.x&&x<=marquee.x+marquee.w&&y>=marquee.y&&y<=marquee.y+marquee.h;}).map(k=>k.id)??[]):[];p.onSelectKeys(b.additive?[...new Set([...p.selectedKeys,...ids])]:ids);setMarquee(null);box.current=null;}
  const ticks=Array.from({length:Math.ceil(duration/(assembling?Math.max(1,Math.ceil(duration/12)):1))+1},(_,i)=>i*(assembling?Math.max(1,Math.ceil(duration/12)):1));
  return <section className="timeline-panel"><div className="timeline-toolbar"><div className="timeline-title"><SlidersHorizontal size={15}/><strong>{tr(assembling?'Master sequence':'Timeline')}</strong><span className="pill">{assembling?`${p.project.sequence.shots.length} shots`:`${p.scene.duration}s`}</span></div><div className="transport"><button title={tr("First frame")} onClick={()=>p.onSeek(0)}><SkipBack size={15}/></button><button title={tr("Play / pause · Space")} className="play-button" onClick={p.onPlay}>{p.playing?<Pause size={15} fill="currentColor"/>:<Play size={15} fill="currentColor"/>}</button><button title={tr("Last frame")} onClick={()=>p.onSeek(duration-1/fps)}><SkipForward size={15}/></button><button title={tr("Loop playback")} className={p.loop?'active':''} onClick={p.onLoop}><Repeat2 size={15}/></button><span className="timecode">{timecode(current,fps)}</span></div><div className="timeline-options"><button title={t('Copy keyframes')} onClick={p.onCopyKeys}>⧉</button><button title={t('Paste keyframes')} onClick={p.onPasteKeys}>▣</button><button title={t('Duplicate keyframes')} onClick={p.onDuplicateKeys}>＋</button><button title={t('Fit duration')} onClick={()=>fit()}>↔</button><button title={t('Fit selection')} onClick={()=>fit(true)}>⌖</button><button title={tr("Previous keyframe")} onClick={()=>jump(-1)}>‹</button><button title={tr("Next keyframe")} onClick={()=>jump(1)}>›</button><button className={`autokey ${p.autoKey?'enabled':''}`} onClick={p.onAutoKey}><span/>{tr("Auto-key")}</button><button title={tr("Add keyframe · K")} onClick={p.onAddKey}><Diamond size={14}/></button><button title={tr("Add marker")} onClick={p.onMarker}><Flag size={14}/></button><button title={tr("Curve editor")} onClick={p.onCurve}><SlidersHorizontal size={14}/></button><span className="divider"/><button onClick={()=>setZoom(z=>Math.max(.25,z/1.25))}><Minus size={13}/></button><button onClick={()=>setZoom(z=>Math.min(8,z*1.25))}><Plus size={13}/></button></div></div>
    <div className="timeline-scroll" ref={content} onPointerMove={boxMove} onPointerUp={boxUp} onPointerCancel={()=>{box.current=null;setMarquee(null);}} onScroll={e=>setScroll(e.currentTarget.scrollTop)}><div className="timeline-content" style={{width:width+220,height:assembling?200:Math.max(205,rows.length*rowHeight+34)}}>
      {marquee&&<div className="timeline-marquee" style={{left:marquee.x,top:marquee.y,width:marquee.w,height:marquee.h}}/>}<div className="ruler-label">{tr(assembling?'PRODUCTION':'LAYERS & CONTROLS')}</div><div className="ruler" style={{width,left:220}} onPointerDown={e=>{seek(e);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(e.buttons===1)seek(e);}}>{ticks.map(t=><span key={t} style={{left:t*pps}}>{assembling?`${Math.floor(t/60)}:${String(t%60).padStart(2,'0')}`:`${t}s`}</span>)}</div>
      {!assembling&&visible.map((row,i)=><div className={`timeline-row ${row.layerId===p.selectedLayer?'selected':''}`} key={row.id} style={{top:34+(i+startRow)*rowHeight,width:width+220}}><div className="timeline-row-label" onClick={()=>p.onSelectLayer(row.layerId)}>{row.group?<button onClick={e=>{e.stopPropagation();p.onToggleLayer(row.layerId);}}>{p.scene.layers.find(l=>l.id===row.layerId)?.collapsed?<ChevronRight size={13}/>:<ChevronDown size={13}/>}</button>:<span className="track-line"/>}{row.group?<span className="layer-color"/>:<Diamond size={10}/>}<span>{row.name}</span></div><div className="timeline-lane" style={{left:220,width}} onPointerDown={boxDown}>{!row.track&&<div className="layer-duration" style={{width:p.scene.duration*pps}}/>}{row.track?.keys.map(k=><button key={k.id} aria-label={`${tr('Keyframe')} ${k.time.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} ${tr('seconds')}`} title={`${k.time.toFixed(2)}s · ${k.ease.mode}`} className={`keyframe ${p.selectedKeys.includes(k.id)?'selected':''} ${k.ease.mode==='hold'?'hold':''}`} style={{left:(k.time+(draft?.ids.includes(k.id)?draft.delta:0))*pps}} onPointerDown={e=>keyDown(e,k)} onPointerMove={keyMove} onPointerUp={keyUp}><Diamond size={12} fill="currentColor"/></button>)}</div></div>)}
      {assembling&&<><div className="sequence-label" style={{top:54}}>{tr("Shots")}</div><div className="sequence-lane" style={{left:220,top:48,width}} onPointerDown={seek}>{p.project.sequence.shots.map(shot=><div className="shot-block" key={shot.id} style={{left:shot.start*pps,width:Math.max(24,shot.duration*pps)}} onPointerDown={e=>{e.stopPropagation();p.onSelectShot(shot.id);const start=e.clientX,original=shot.start;e.currentTarget.setPointerCapture(e.pointerId);const el=e.currentTarget;el.onpointermove=ev=>{if(ev.buttons===1)el.style.left=`${Math.max(0,original+(ev.clientX-start)/pps)*pps}px`;};el.onpointerup=ev=>{p.onShot(shot.id,Math.round(Math.max(0,original+(ev.clientX-start)/pps)*fps)/fps);el.onpointermove=null;el.onpointerup=null;};}}><span>{p.project.scenes.find(s=>s.id===shot.sceneId)?.name}</span><small>{shot.duration.toFixed(1)}{tr("s")}</small></div>)}</div><div className="sequence-label" style={{top:122}}><Music2 size={13}/> {tr("Audio")}</div><div className="sequence-lane audio-lane" style={{left:220,top:111,width}} onPointerDown={seek}>{p.project.sequence.audio.map(clip=>{const asset=p.project.assets.find(a=>a.id===clip.assetId);return <div className="audio-block" key={clip.id} style={{left:clip.start*pps,width:Math.max(30,clip.duration*pps)}} onPointerDown={e=>{e.stopPropagation();p.onSelectAudio(clip.id);const start=e.clientX,original=clip.start;e.currentTarget.setPointerCapture(e.pointerId);const el=e.currentTarget;el.onpointermove=ev=>{if(ev.buttons===1)el.style.left=`${Math.max(0,original+(ev.clientX-start)/pps)*pps}px`;};el.onpointerup=ev=>{p.onAudio(clip.id,Math.round(Math.max(0,original+(ev.clientX-start)/pps)*fps)/fps);el.onpointermove=null;el.onpointerup=null;};}}><span>{asset?.name}</span><svg viewBox="0 0 500 24" preserveAspectRatio="none">{asset?.waveform?.filter((_,i)=>i%4===0).map((v,i)=><line key={i} x1={i*2} x2={i*2} y1={12-v*11} y2={12+v*11} stroke="currentColor"/>)}</svg></div>;})}</div></>}
      {!assembling&&p.scene.markers.map(m=><div className="timeline-marker" key={m.id} style={{left:220+m.time*pps}} title={m.label}><Flag size={12}/><span>{m.label}</span></div>)}
      <div className="playhead" style={{left:220+current*pps,height:assembling?190:Math.max(205,rows.length*rowHeight+34)}}><span/></div>
    </div></div><div className="snap-controls">{['Frames','Playhead','Markers','Keys'].map(key=><label key={key}><input type="checkbox" checked={!!snap[key]} onChange={e=>{const next={...snap,[key]:e.target.checked};setSnap(next);localStorage.setItem('fio.snapping',JSON.stringify(next));}}/>{tr(key)}</label>)}{p.autoKey&&<strong>{t('Auto-key records movement')}</strong>}</div><div className="timeline-footnote"><span>{assembling?'Drag shots and audio to arrange your story':'Select keyframes · Shift to select more · Drag to adjust timing'}</span><span>{p.project.fps.numerator/p.project.fps.denominator} {tr("fps")} <span className="status-dot"/> {tr("Smooth interpolation")}</span></div>
  </section>;
}
