import {cp,mkdir,readFile,writeFile,stat} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {fetchManifest,validateManifest} from './releases.mjs';
const root=path.dirname(fileURLToPath(import.meta.url)),out=path.join(root,'dist');
const offline=process.argv.includes('--offline');
const release=offline?validateManifest(JSON.parse(await readFile(path.join(root,'release.json'),'utf8'))):await fetchManifest();
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const size=bytes=>bytes<1024?`${bytes} B`:`${(bytes/1000/1000).toFixed(bytes>1000000?1:2)} MB`;
const rows=release.assets.map(a=>`<a class="download-row" href="${escape(a.url)}" data-download="${a.id}"><span><strong>${escape(a.label)}</strong><small>${escape(a.description)}</small></span><span>${size(a.bytes)} <b aria-hidden="true">↗</b></span></a>`).join('\n');
const notice=`<span class="release-label">${escape(release.version)} · ${release.prerelease?'Release candidate':'Stable release'}</span><br>${release.prerelease?'This build is for testing. Check the release notes for known limitations. ':''}${release.unsigned?'The executables are unsigned; Windows may display a trust warning. ':''}<a href="${escape(release.url)}">Read the release notes.</a>`;
const replacements={__INSTALLER_URL__:release.assets.find(a=>a.id==='installer').url,__RELEASE_BADGE__:release.version+(release.prerelease?' · Test candidate':''),__RELEASE_NOTICE__:notice,__DOWNLOADS__:rows,__RELEASE_URL__:release.url,__SIGNING_FAQ__:release.unsigned?'This build is unsigned. Windows may show a trust or SmartScreen warning.':'Windows can show a trust or SmartScreen warning. Check the release notes for this build’s signing status.'};
const html=(await readFile(path.join(root,'index.html'),'utf8')).replace(/__[A-Z_]+__/g,key=>replacements[key]??(()=>{throw Error('Unknown placeholder '+key)})());
if(/__[A-Z_]+__/.test(html))throw Error('Unresolved website template.');
for(const file of ['editor.png','connections.png','easing.png','assemble.png','hero-poster.png','social-preview.png','icon.png'])await stat(path.join(root,'assets/images',file));
for(const [file,limit]of [['hero.mp4',4*1024*1024],['demo.mp4',15*1024*1024]])if((await stat(path.join(root,'assets/video',file))).size>limit)throw Error(file+' exceeds media budget.');
if((await stat(path.join(root,'assets/images/social-preview.png'))).size>=1000000)throw Error('Social preview exceeds 1 MB.');
await mkdir(out,{recursive:true});await cp(path.join(root,'assets'),path.join(out,'assets'),{recursive:true});await cp(path.join(root,'guide'),path.join(out,'guide'),{recursive:true});await cp(path.join(root,'404.html'),path.join(out,'404.html'));
await writeFile(path.join(out,'index.html'),html);await writeFile(path.join(out,'downloads.json'),JSON.stringify(release,null,2)+'\n');
await writeFile(path.join(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://justypixels.github.io/fio-motion/</loc></url><url><loc>https://justypixels.github.io/fio-motion/guide/</loc></url></urlset>\n');
await writeFile(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://justypixels.github.io/fio-motion/sitemap.xml\n');
await writeFile(path.join(out,'.nojekyll'),'');
console.log(`Website built for ${release.version}${offline?' (offline metadata)':''}. Output: website/dist`);
