import { type Asset, type Project } from './model';
import { audioGain } from './animation';
export class AudioEngine {
  context = new AudioContext({ sampleRate: 48000 }); private buffers = new Map<string, AudioBuffer>(); private sources: AudioBufferSourceNode[]=[]; private epoch=0; private offset=0;
  async decode(asset:Asset){const old=this.buffers.get(asset.id);if(old)return old;const buffer=await this.context.decodeAudioData(await(await fetch(asset.data)).arrayBuffer());this.buffers.set(asset.id,buffer);return buffer;}
  async analyze(asset:Asset){const b=await this.decode(asset),samples=b.getChannelData(0),waveform:number[]=[];const size=Math.ceil(samples.length/1000);for(let i=0;i<1000;i++){let max=0;for(let j=i*size;j<Math.min((i+1)*size,samples.length);j++)max=Math.max(max,Math.abs(samples[j]));waveform.push(max);}return {duration:b.duration,waveform};}
  private async schedule(project:Project,ctx:BaseAudioContext,start:number,end:number,clock:number){
    for(const clip of project.sequence.audio){const asset=project.assets.find(a=>a.id===clip.assetId);if(!asset)continue;const buffer=await this.decode(asset),at=Math.max(start,clip.start),until=Math.min(end,clip.start+clip.duration),sourceOffset=clip.sourceIn+at-clip.start,duration=Math.min(until-at,buffer.duration-sourceOffset);if(duration<=0||sourceOffset<0)continue;const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;source.connect(gain);gain.connect(ctx.destination);const when=clock+at-start;gain.gain.setValueAtTime(audioGain(clip,at),when);const knots=[at,at+duration,clip.start+clip.fadeIn,clip.start+clip.duration-clip.fadeOut,...clip.volumeKeys.map(k=>clip.start+k.time)].filter(t=>t>=at&&t<=at+duration).sort((a,b)=>a-b);for(let segment=1;segment<knots.length;segment++){const a=knots[segment-1],b=knots[segment],fading=a<clip.start+clip.fadeIn||b>clip.start+clip.duration-clip.fadeOut,steps=fading?Math.max(1,Math.ceil((b-a)*50)):1;for(let i=1;i<=steps;i++){const t=a+(b-a)*i/steps;gain.gain.linearRampToValueAtTime(audioGain(clip,Math.min(t,clip.start+clip.duration-1e-7)),clock+t-start);}}source.start(when,sourceOffset,duration);if(ctx===this.context)this.sources.push(source);}
  }
  async play(project:Project,time:number,sequence:boolean){this.stop();await this.context.resume();if(sequence){const ids=new Set(project.sequence.audio.filter(c=>c.start+c.duration>time).map(c=>c.assetId));for(const id of ids){const asset=project.assets.find(a=>a.id===id);if(asset)await this.decode(asset);}}this.offset=time;this.epoch=this.context.currentTime+.05;if(sequence)await this.schedule(project,this.context,time,Infinity,this.epoch);}
  get time(){return this.offset+Math.max(0,this.context.currentTime-this.epoch);}
  stop(){for(const source of this.sources){try{source.stop();}catch{}}this.sources=[];}
  async mix(project:Project,start:number,end:number):Promise<string|undefined>{if(!project.sequence.audio.length)return;const ctx=new OfflineAudioContext(2,Math.ceil((end-start)*48000),48000);await this.schedule(project,ctx,start,end,0);const rendered=await ctx.startRendering(),length=rendered.length*4,bytes=new ArrayBuffer(44+length),view=new DataView(bytes);const text=(at:number,s:string)=>{for(let i=0;i<s.length;i++)view.setUint8(at+i,s.charCodeAt(i));};text(0,'RIFF');view.setUint32(4,36+length,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,2,true);view.setUint32(24,48000,true);view.setUint32(28,192000,true);view.setUint16(32,4,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,length,true);const a=rendered.getChannelData(0),b=rendered.getChannelData(1);for(let i=0;i<rendered.length;i++){view.setInt16(44+i*4,Math.max(-1,Math.min(1,a[i]))*32767,true);view.setInt16(46+i*4,Math.max(-1,Math.min(1,b[i]))*32767,true);}const blob=new Blob([bytes],{type:'audio/wav'});return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result as string);reader.onerror=reject;reader.readAsDataURL(blob);});}
}
