export const helpRows=`
Meet your little explorer|Conheça sua pequena raposa|Conoce a tu pequeño explorador|Découvrez votre petit explorateur|Lernen Sie Ihren kleinen Entdecker kennen|小さな探検家に会おう|认识小小探险家
Press Space to play the sample wave. The artwork is split into layers, and the right arm already has a simple puppet rig.|Pressione Espaço para reproduzir o aceno. A arte está em camadas e o braço direito já tem um rig simples.|Pulsa Espacio para reproducir el saludo. La ilustración tiene capas y el brazo derecho ya tiene un rig sencillo.|Appuyez sur Espace pour lire le salut. L’illustration est en calques et le bras droit possède déjà un rig simple.|Drücken Sie die Leertaste für das Winken. Die Grafik besteht aus Ebenen; der rechte Arm hat ein einfaches Rig.|スペースキーでサンプルの手振りを再生します。画像はレイヤーに分かれ、右腕にはリグがあります。|按空格播放挥手示例。图稿分为多个图层，右臂已有简单绑定。
Play the wave|Reproduzir o aceno|Reproducir el saludo|Lire le salut|Winken abspielen|手振りを再生|播放挥手
Give artwork a few controls|Adicione controles à arte|Añade controles a la ilustración|Ajoutez des contrôles à l’illustration|Grafik mit Steuerelementen versehen|画像にコントロールを追加|给图稿添加控制器
Open Rig, select a layer, and choose Movement pin. Add an Anchor where the artwork should stay still. Drag movement pins to test the bend.|Abra Rig, selecione uma camada e escolha Pin de movimento. Adicione uma Âncora onde a arte deve ficar parada. Arraste pins para testar a dobra.|Abre Rig, selecciona una capa y elige Pin de movimiento. Añade un Ancla donde la ilustración deba quedar fija. Arrastra los pins para probar la flexión.|Ouvrez Rig, sélectionnez un calque et un point de mouvement. Ajoutez un ancrage aux zones fixes, puis faites glisser les points pour tester la flexion.|Öffnen Sie Rig und wählen Sie Ebene und Bewegungs-Pin. Setzen Sie einen Anker an festen Stellen und ziehen Sie Pins zum Testen.|Rigでレイヤーと移動ピンを選びます。動かしたくない場所に固定ピンを追加し、ピンをドラッグして曲がり方を確認します。|打开绑定工作区，选择图层和移动图钉。在固定位置添加锚点，拖动图钉测试弯曲。
Open Rig|Abrir Rig|Abrir Rig|Ouvrir Rig|Rig öffnen|Rigを開く|打开绑定工作区
Make a pose, then another|Crie uma pose, depois outra|Crea una pose, luego otra|Créez une pose, puis une autre|Eine Pose, dann die nächste|ポーズを作って動かす|创建连续姿势
Open Animate and keep Auto-key enabled. Move the playhead, drag the hand pin, then play. Smooth easing is applied automatically.|Abra Animar com Auto-key ligado. Mova o indicador de tempo, arraste o pin da mão e reproduza. A suavização é aplicada automaticamente.|Abre Animar con la clave automática activada. Mueve el cabezal, arrastra el pin de la mano y reproduce. El suavizado se aplica automáticamente.|Ouvrez Animer avec la clé automatique activée. Déplacez la tête de lecture et le point de la main, puis lancez la lecture. Le mouvement est adouci automatiquement.|Öffnen Sie Animieren mit Auto-Key. Versetzen Sie die Abspielposition und ziehen Sie den Hand-Pin. Die Bewegung wird automatisch geglättet.|アニメーションで自動キーを有効にし、再生ヘッドを動かして手のピンをドラッグします。滑らかな補間が自動で適用されます。|打开动画工作区并启用自动关键帧。移动播放头、拖动手部图钉后播放，系统会自动应用平滑缓动。
Open Animate|Abrir Animar|Abrir Animar|Ouvrir Animer|Animieren öffnen|アニメーションを開く|打开动画工作区
Make the timing your own|Ajuste o ritmo|Ajusta el ritmo|Personnalisez le rythme|Timing gestalten|タイミングを調整|调整节奏
Select a diamond on the timeline. Drag the timing-curve handles to change acceleration, or add spatial handles to bend the motion path.|Selecione um losango na timeline. Arraste as alças da curva para ajustar a aceleração ou adicione alças espaciais para mudar a trajetória.|Selecciona un rombo en la línea de tiempo. Arrastra los controles de curva para ajustar la aceleración o añade controles espaciales para cambiar la trayectoria.|Sélectionnez un losange dans la chronologie. Ajustez les poignées temporelles pour l’accélération ou les poignées spatiales pour la trajectoire.|Wählen Sie eine Raute in der Zeitleiste. Zeitkurvengriffe ändern die Beschleunigung; räumliche Griffe ändern den Pfad.|タイムラインのひし形を選びます。時間カーブで加速を、軌道ハンドルで動きの経路を調整します。|选择时间轴上的菱形，拖动时间曲线手柄调整加速，或添加空间手柄改变运动路径。
Show timing curve|Mostrar curva de tempo|Mostrar curva de tiempo|Afficher la courbe temporelle|Zeitkurve anzeigen|時間カーブを表示|显示时间曲线
Turn shots into a story|Transforme cenas numa história|Convierte escenas en una historia|Transformez les plans en histoire|Szenen zu einer Geschichte verbinden|ショットを物語にする|将镜头组合成故事
Assemble puts your shots and audio on one timeline. When you are ready, export an MP4 or transparent PNG sequence.|Montar reúne cenas e áudio numa timeline. Quando terminar, exporte MP4 ou uma sequência PNG transparente.|Montar reúne escenas y audio en una línea de tiempo. Al terminar, exporta MP4 o una secuencia PNG transparente.|Assembler réunit plans et audio dans une chronologie. Exportez ensuite un MP4 ou une séquence PNG transparente.|Zusammenstellen verbindet Szenen und Audio. Exportieren Sie anschließend MP4 oder eine transparente PNG-Sequenz.|構成ではショットと音声をまとめます。完成したらMP4または透明PNG連番で書き出します。|合成工作区将镜头和音频放入同一时间轴，完成后导出MP4或透明PNG序列。
Open Assemble|Abrir Montar|Abrir Montar|Ouvrir Assembler|Zusammenstellen öffnen|構成を開く|打开合成工作区
Your story starts with artwork.|Sua história começa com a arte.|Tu historia comienza con la ilustración.|Votre histoire commence par une illustration.|Ihre Geschichte beginnt mit einer Grafik.|物語は画像から始まります。|故事从图稿开始。
Import an image or PSD|Importar imagem ou PSD|Importar imagen o PSD|Importer une image ou un PSD|Bild oder PSD importieren|画像またはPSDを読み込む|导入图像或PSD
A recovery snapshot is available from|Há uma cópia de recuperação de|Hay una copia de recuperación de|Une copie de récupération est disponible du|Eine Wiederherstellung ist verfügbar vom|復元データがあります：|存在恢复快照：
Your project|Seu projeto|Tu proyecto|Votre projet|Ihr Projekt|プロジェクト|您的项目
Finish your animation|Finalize sua animação|Termina tu animación|Terminez votre animation|Animation fertigstellen|アニメーションを完成させる|完成动画
A little movement goes a long way|Um pequeno movimento faz a diferença|Un pequeño movimiento marca la diferencia|Un petit mouvement fait la différence|Kleine Bewegungen bewirken viel|小さな動きが作品を変える|小动作，大不同
A little imagination. A lot of possibility.|Um pouco de imaginação. Muitas possibilidades.|Un poco de imaginación. Muchas posibilidades.|Un peu d’imagination. Beaucoup de possibilités.|Etwas Fantasie. Viele Möglichkeiten.|少しの想像力で、たくさんの可能性。|一点想象，无限可能。
Make it once. Bring it to life again.|Crie uma vez. Dê vida novamente.|Crea una vez. Dale vida de nuevo.|Créez une fois. Animez à nouveau.|Einmal erstellen. Immer wieder beleben.|一度作って、何度でも動かす。|创作一次，反复赋予生命。
From a little idea to a finished story.|De uma pequena ideia a uma história completa.|De una pequeña idea a una historia completa.|D’une petite idée à une histoire complète.|Von einer kleinen Idee zur fertigen Geschichte.|小さなアイデアから完成した物語へ。|从小小创意到完整故事。
Frame your story|Enquadre sua história|Encuadra tu historia|Cadrez votre histoire|Geschichte ins Bild setzen|物語を画面に収める|构建故事画面
fps · every frame rendered at full quality|fps · todos os frames em qualidade completa|fps · todos los fotogramas a máxima calidad|fps · chaque image en qualité maximale|fps · jeder Frame in voller Qualität|fps · 全フレームを最高品質で描画|fps · 每帧以完整质量渲染
selected|selecionados|seleccionados|sélectionnés|ausgewählt|選択中|已选中
layers|camadas|capas|calques|Ebenen|レイヤー|图层
vertices|vértices|vértices|sommets|Vertices|頂点|顶点
control|controle|control|contrôle|Steuerelement|コントロール|控制器
Inspector|Propriedades|Propiedades|Propriétés|Eigenschaften|プロパティ|属性
Project|Projeto|Proyecto|Projet|Projekt|プロジェクト|项目
Shot|Cena|Escena|Plan|Szene|ショット|镜头
Camera|Câmera|Cámara|Caméra|Kamera|カメラ|摄像机
Audio Clip|Clipe de áudio|Clip de audio|Clip audio|Audioclip|音声クリップ|音频片段
Lesson|Lição|Lección|Leçon|Lektion|レッスン|课程
End|Fim|Fin|Fin|Ende|終了|结束
Pieces Following This Layer|Peças que seguem esta camada|Piezas que siguen esta capa|Pièces suivant ce calque|Teile, die dieser Ebene folgen|このレイヤーに追従するパーツ|跟随此图层的部件
Enable Auto-key or move to an existing keyframe before changing this animated control.|Ative Auto-key ou vá a um keyframe existente para alterar este controle.|Activa la clave automática o ve a una clave existente para cambiar este control.|Activez la clé automatique ou allez à une image clé existante pour modifier ce contrôle.|Aktivieren Sie Auto-Key oder wechseln Sie zu einem bestehenden Keyframe.|自動キーを有効にするか、既存のキーフレームに移動してください。|请启用自动关键帧或移至已有关键帧后修改此控制器。
Select an image layer first.|Selecione uma camada de imagem primeiro.|Selecciona primero una capa de imagen.|Sélectionnez d’abord un calque d’image.|Wählen Sie zuerst eine Bildebene.|最初に画像レイヤーを選択してください。|请先选择图像图层。
Place new controls in the Rig workspace.|Adicione controles no workspace Rig.|Añade controles en Rig.|Ajoutez les contrôles dans Rig.|Neue Steuerelemente in Rig hinzufügen.|新しいコントロールはRigで配置してください。|请在绑定工作区添加控制器。
Draw new bones in the Rig workspace.|Desenhe ossos no workspace Rig.|Dibuja huesos en Rig.|Dessinez les os dans Rig.|Neue Knochen in Rig zeichnen.|新しいボーンはRigで描いてください。|请在绑定工作区绘制骨骼。
Edit piece connections in the Rig workspace.|Edite conexões no workspace Rig.|Edita las conexiones en Rig.|Modifiez les connexions dans Rig.|Verbindungen in Rig bearbeiten.|接続はRigで編集してください。|请在绑定工作区编辑连接。
Shared skeleton bones are managed by the character assistant.|O esqueleto compartilhado é gerenciado pelo assistente de personagem.|El esqueleto compartido se administra con el asistente.|Le squelette partagé est géré par l’assistant de personnage.|Das gemeinsame Skelett wird vom Figurenassistenten verwaltet.|共有スケルトンはキャラクターアシスタントで管理します。|共享骨架由角色向导管理。
Choose a whole limb or separate segments, not both.|Escolha um membro inteiro ou segmentos separados, não os dois.|Elige un miembro completo o segmentos separados, no ambos.|Choisissez un membre entier ou des segments, pas les deux.|Wählen Sie einen ganzen Arm/ein Bein oder Segmente, nicht beides.|全体の手足と分割パーツを同時に選択しないでください。|请选择完整肢体或分段部件，不要同时选择。
These pieces would create a circular rig connection.|Estas peças criariam uma conexão circular.|Estas piezas crearían una conexión circular.|Ces pièces créeraient une connexion circulaire.|Diese Teile würden eine zyklische Verbindung erzeugen.|循環接続になるため接続できません。|这些部件会形成循环连接。
The connection target is unavailable.|O destino da conexão não está disponível.|El destino de conexión no está disponible.|La cible de connexion est indisponible.|Das Verbindungsziel ist nicht verfügbar.|接続先が利用できません。|连接目标不可用。
Reset the target scale before connecting this piece.|Restaure a escala do destino antes de conectar.|Restablece la escala del destino antes de conectar.|Réinitialisez l’échelle de la cible avant de connecter.|Setzen Sie die Zielskalierung vor dem Verbinden zurück.|接続前に接続先の拡大率をリセットしてください。|连接前请重置目标缩放。
Reset the piece scale before connecting it.|Restaure a escala da peça antes de conectar.|Restablece la escala de la pieza antes de conectar.|Réinitialisez l’échelle de la pièce avant de connecter.|Setzen Sie die Teilskalierung vor dem Verbinden zurück.|接続前にパーツの拡大率をリセットしてください。|连接前请重置部件缩放。
Import PNG, JPEG, WebP, or PSD artwork.|Importe arte PNG, JPEG, WebP ou PSD.|Importa ilustraciones PNG, JPEG, WebP o PSD.|Importez des illustrations PNG, JPEG, WebP ou PSD.|Importieren Sie PNG-, JPEG-, WebP- oder PSD-Grafiken.|PNG、JPEG、WebP、PSDを読み込めます。|请导入PNG、JPEG、WebP或PSD图稿。
This artwork file exceeds the 512 MB limit.|Esta arte excede o limite de 512 MB.|Esta ilustración supera el límite de 512 MB.|Cette illustration dépasse la limite de 512 Mo.|Diese Grafik überschreitet 512 MB.|画像ファイルが512MBを超えています。|图稿文件超过512MB限制。
Artwork dimensions must be at most 8192 pixels.|A arte deve ter no máximo 8192 pixels por dimensão.|La ilustración debe tener como máximo 8192 píxeles por dimensión.|L’illustration doit mesurer au maximum 8192 pixels par dimension.|Die Grafik darf pro Dimension höchstens 8192 Pixel haben.|画像の各辺は8192ピクセル以下にしてください。|图稿每边不得超过8192像素。
Replacement artwork must have the same dimensions to preserve this rig.|A nova arte deve ter as mesmas dimensões para preservar o rig.|La nueva ilustración debe tener las mismas dimensiones para conservar el rig.|La nouvelle illustration doit garder les dimensions pour préserver le rig.|Die Ersatzgrafik muss dieselben Abmessungen haben, um das Rig zu erhalten.|リグを維持するには同じサイズの画像を使用してください。|替换图稿必须尺寸相同才能保留绑定。
This layer has no visible pixels to rig.|Esta camada não tem pixels visíveis para criar rig.|Esta capa no tiene píxeles visibles para el rig.|Ce calque n’a aucun pixel visible pour le rig.|Diese Ebene hat keine sichtbaren Pixel für ein Rig.|このレイヤーにはリグを作れる可視ピクセルがありません。|此图层没有可用于绑定的可见像素。
Please save this PSD as 8-bit RGB, with dimensions no larger than 8192 pixels. PSB is not supported.|Salve o PSD como RGB de 8 bits, com dimensões até 8192 pixels. PSB não é suportado.|Guarda el PSD como RGB de 8 bits, con dimensiones hasta 8192 píxeles. PSB no es compatible.|Enregistrez le PSD en RVB 8 bits, avec des dimensions maximales de 8192 pixels. PSB n’est pas pris en charge.|Speichern Sie PSD als 8-Bit-RGB mit höchstens 8192 Pixeln je Seite. PSB wird nicht unterstützt.|PSDは8ビットRGB、各辺8192ピクセル以下で保存してください。PSBは非対応です。|请将PSD保存为8位RGB，每边不超过8192像素。不支持PSB。
The export range must contain at least one frame.|O intervalo de exportação deve conter ao menos um frame.|El intervalo debe contener al menos un fotograma.|La plage d’export doit contenir au moins une image.|Der Exportbereich muss mindestens einen Frame enthalten.|書き出し範囲には最低1フレーム必要です。|导出范围必须至少包含一帧。
The beta supports exports up to 3840 × 2160.|A versão suporta exportação até 3840 × 2160.|La versión admite exportación hasta 3840 × 2160.|La version prend en charge l’export jusqu’à 3840 × 2160.|Diese Version unterstützt Export bis 3840 × 2160.|このバージョンは3840×2160までの書き出しに対応します。|此版本支持最高3840×2160导出。
Building mesh…|Criando malha…|Creando malla…|Création du maillage…|Netz wird erstellt…|メッシュを生成中…|正在生成网格…
Importing artwork…|Importando arte…|Importando ilustración…|Importation de l’illustration…|Grafik wird importiert…|画像を読み込み中…|正在导入图稿…
Connecting character pieces…|Conectando peças…|Conectando piezas…|Connexion des pièces…|Teile werden verbunden…|パーツを接続中…|正在连接部件…
Rebuilding mesh…|Reconstruindo malha…|Reconstruyendo malla…|Reconstruction du maillage…|Netz wird neu erstellt…|メッシュを再構築中…|正在重建网格…
Reading audio…|Lendo áudio…|Leyendo audio…|Lecture de l’audio…|Audio wird gelesen…|音声を読み込み中…|正在读取音频…
Preparing bone weights…|Preparando pesos…|Preparando pesos…|Préparation des poids…|Knochengewichte werden vorbereitet…|ウェイトを準備中…|正在准备骨骼权重…
`;
